pfcp:
  local_addr: 147.175.185.199 # IP addr for listening
  remote_addr: 147.175.185.199
  node_id: 147.175.185.199 # External IP or FQDN can be reached
  ret_timeout: 1s # retransmission timeout
  max_ret: 3 # the max number of retransmission

gtpu:
  addr: 147.175.185.199

api:
  addr: "0.0.0.0"
  port: 8080
  prefix: "/api/v1/"

logger: # log output setting
  name: raxupf
  level: debug
